[workspace]
allow_dirty = false
changelog_path = "CHANGELOG.md"
changelog_update = true
dependencies_update = false
git_release_enable = false
git_tag_enable = false
pr_branch_prefix = "release-plz-"
publish = false
release_always = false
semver_check = true
